[package]
name = "ceres-cli"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"


[[bin]]
name = "ceres"
path = "bin/ceres.rs"


[dependencies]
etc = "0.1.16"
hex = "0.4.3"
dirs = "3.0.1"
sled = "0.34.6"
serde = { version = "1.0.125", features = ["derive"] }
bincode = "1.3.3"
thiserror = "1.0.24"
structopt = "0.3.21"

# ceres deps
ceres-std = { path = "crates/std", features = [ "std" ] }
ceres-runtime = { path = "crates/runtime", features = [ "std" ] }
ceres-sandbox = { path = "crates/sandbox", features = [ "std" ] }


[dev-dependencies]
parity-wasm = "0.41.0"
serde_json = "1.0.64"
wat = "1.0.37"
parity-scale-codec = "2"

# ceres dev
ceres-executor = { path = "crates/executor", features = [ "std" ] }
ceres-seal = { path = "crates/seal", features = [ "std" ]}
ceres-ri = { path = "crates/ri", features = [ "std" ]}


[workspace]
members = [
  "crates/ri",
  "crates/std",
  "crates/seal",
  "crates/derive",
  "crates/sandbox",
  "crates/runtime",
  "crates/executor",
]


[profile.release]
codegen-units=1

[patch.crates-io]
parity-wasm = { git = "https://github.com/patractlabs/parity-wasm", branch = "v0.41.0" }