[patch.crates-io]
parity-wasm = { git = "https://github.com/patractlabs/parity-wasm", branch = "v0.41.0" }

[workspace]
members = [
  "executor",
  "runtime",
  "std",
]

# For the testing contracts
exclude = [
  "contracts"
]