[patch.crates-io]
parity-wasm = { git = "https://github.com/patractlabs/parity-wasm", branch = "v0.41.0" }

[workspace]
members = [
  "std",
  "seal",
  "derive",
  "sandbox",
  "runtime",
  "executor",
]

# For the testing contracts
exclude = [
  "contracts"
]