[patch.crates-io]
parity-wasm = { git = "https://github.com/patractlabs/parity-wasm", branch = "v0.41.0" }

[workspace]
members = [
  "derive",
  "proxy",
  "runtime",
]

# For the testing contracts
exclude = [
  "contracts"
]