[package]
name = "ceres-seal"
version = "0.2.0"
edition = "2018"
authors = [
  "Patract <hi@patract.io>",
  "clearloop <udtrokia@gmail.com>"
]
description = "ceres runtime interfaces"
repository = "https://github.com/patractlabs/ceres"
license = "MIT"
readme = './README.md'
keywords = ["wasm", "substrate", "runtime"]

[dependencies]
log = "0.4.14"
ceres-std = { path = "../std", version = "^0" }
ceres-derive = { path = "../derive", version = "^0" }
ceres-sandbox = { path = "../sandbox", version = "^0" }
ceres-executor = { path = "../executor", version = "^0" }

parity-scale-codec = { version = "2", features = ["derive"]}

[features]
default = []
std = [
    "ceres-std/std",
    "ceres-sandbox/std",
    "ceres-executor/std",
]
