[package]
name = "ceres-cli"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[[bin]]
name = "ceres"
path = "bin/ceres.rs"

[dependencies]
hex = "0.4.3"
thiserror = "1.0.24"
structopt = "0.3.21"

# ceres deps
ceres-runtime = { path = "../runtime", features = [ "std" ] }
ceres-sandbox = { path = "../sandbox", features = [ "std" ] }