[package]
name = "ceres-cli"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[[bin]]
name = "ceres"
path = "bin/ceres.rs"

[dependencies]
etc = "0.1.16"
hex = "0.4.3"
dirs = "3.0.1"
sled = "0.34.6"
serde = { version = "1.0.125", features = ["derive"] }
bincode = "1.3.3"
thiserror = "1.0.24"
structopt = "0.3.21"

# ceres deps
ceres-std = { path = "../std", features = [ "std" ] }
ceres-runtime = { path = "../runtime", features = [ "std" ] }
ceres-sandbox = { path = "../sandbox", features = [ "std" ] }