[package]
name = "ceres-executor"
version = "0.1.0"
edition = "2018"
authors = [
  "Patract <hi@patract.io>",
  "clearloop <udtrokia@gmail.com>"
]
description = "wasm executor of ceres"
repository = "https://github.com/patractlabs/ceres"
license = "MIT"
readme = './README.md'
keywords = ["wasm", "substrate", "runtime"]

[dependencies]
wasmi = { package = "patract-wasmi", optional = true, version = "^0" }
wasmtime = { version = "0.26.0", optional = true }
anyhow = { version = "1", default-features = false }

# ceres dependencies
ceres-std = { path = "../std", version = "^0" }

[features]
default = [ "wasmi" ]
std = [
    "ceres-std/std" ,
    "wasmtime",
]
