[package]
name = "ceres-executor"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[dependencies]
wasmi = { git = "https://github.com/patractlabs/wasmi.git", branch = "v0.7.0", optional = true }
wasmtime = { version = "0.26.0", optional = true }

# ceres dependencies
ceres-std = { path = "../std" }

[features]
default = [ "wasmi" ]
std = [
    "ceres-std/std" ,
    "wasmtime",
]
