name: Ceres

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ceres:
    if: "! contains(toJSON(github.event.commits.head_commit.message), 'ci(skip)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Cache Rust Outputs
        uses: actions/cache@v1
        env:
          cache-name: rust-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Build && Test
        run: cargo test --all --all-features
