name: Ceres

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  wasm-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Set nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Cache Rust Outputs
        uses: actions/cache@v1
        env:
          cache-name: rust-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Download wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build Web
        run: cd browser && yarn build
      - name: Downlaod Firefox
        run: sudo apt-get update && sudo apt-get install firefox xvfb
      - name: Test browser intergration
        run: cd browser && wasm-pack test --firefox --headless

